Update action.yaml

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -18,12 +18,11 @@ jobs:
       - name: Validate OpenAPI specs
         run: |
           for file in examples/*.yaml; do
-            echo "Validating $file..."
-            if swagger-cli validate --verbose "$file" > "$file.log" 2>&1; then
-              echo "Validation succeeded for $file"
-            else
-              echo "::error file=$file::Validation failed for $file"
-            fi
+          echo "Validating $file..."
+          result=$(swagger-cli validate --json "$file" 2>&1) || echo "::error file=$file::Validation failed for $file"
+          if [[ "$result" != "[]" ]]; then
+          echo "$result" | jq '.[] | {message, path, line: .range.start.line, column: .range.start.column}' | jq -s
+          fi
           done
 
       - name: Upload validation logs
